class Product {
  final String price1, price2, text1, text2, text3, text4,text5,text6,text7, image, image2;
  Product(
      {this.price1,
      this.price2,
      this.text1,
      this.text2,
      this.text3,
      this.text4,
        this.text5,
        this.text6,
        this.text7,
      this.image,
      this.image2});
}

List<Product> productAll = [
  Product(
      price1: "399.000 d",
      price2: "600.000 d",
      text1: "KAYOKO",
      text2: "Bộ mỹ phẩm Kayko",
      text3: "Trị Nám Da Số Một",
      text4: "Nhật Bản Chính Hãng",
      text5: "Mặt nạ giấy - sử dụng nhưu thế nào ...",
      text6: "Làn sóng đắp mặt nạ giấy  không chỉ  loan khắp  nước hàn quốc .mà còn trở thành  xu hướng  của nhiều  cô gái việt .Thế nhưng, đắp mặt nạ giấy...",
      text7: "15 ngày trước",
      image: "assets/images/image_list_one.png",
      image2: "assets/images/list_two.png"),
  Product(
      price1: "399.000 d",
      price2: "600.000 d",
      text1: "KAYOKO",
      text2: "Bộ mỹ phẩm Kayko",
      text3: "Trị Nám Da Số Một",
      text4: "Nhật Bản Chính Hãng",
      text5: "Mặt nạ giấy - sử dụng nhưu thế nào ...",
      text6: "Làn sóng đắp mặt nạ giấy  không chỉ  loan khắp  nước hàn quốc .mà còn trở thành  xu hướng  của nhiều  cô gái việt .Thế nhưng, đắp mặt nạ giấy...",
      text7: "15 ngày trước",
      image: "assets/images/image_list_one.png",
      image2: "assets/images/list_two.png"),
  Product(
      price1: "399.000 d",
      price2: "600.000 d",
      text1: "KAYOKO",
      text2: "Bộ mỹ phẩm Kayko",
      text3: "Trị Nám Da Số Một",
      text4: "Nhật Bản Chính Hãng",
      text5: "Mặt nạ giấy - sử dụng nhưu thế nào ...",
      text6: "Làn sóng đắp mặt nạ giấy  không chỉ  loan khắp  nước hàn quốc .mà còn trở thành  xu hướng  của nhiều  cô gái việt .Thế nhưng, đắp mặt nạ giấy...",
      text7: "15 ngày trước",
      image: "assets/images/image_list_one.png",
      image2: "assets/images/list_two.png"),
  Product(
      price1: "399.000 d",
      price2: "600.000 d",
      text1: "KAYOKO",
      text2: "Bộ mỹ phẩm Kayko",
      text3: "Trị Nám Da Số Một",
      text4: "Nhật Bản Chính Hãng",
      text5: "Mặt nạ giấy - sử dụng nhưu thế nào ...",
      text6: "Làn sóng đắp mặt nạ giấy  không chỉ  loan khắp  nước hàn quốc .mà còn trở thành  xu hướng  của nhiều  cô gái việt .Thế nhưng, đắp mặt nạ giấy...",
      text7: "15 ngày trước",
      image: "assets/images/image_list_one.png",
      image2: "assets/images/list_two.png"),
  Product(
      price1: "399.000 d",
      price2: "600.000 d",
      text1: "KAYOKO",
      text2: "Bộ mỹ phẩm Kayko",
      text3: "Trị Nám Da Số Một",
      text4: "Nhật Bản Chính Hãng",
      text5: "Mặt nạ giấy - sử dụng nhưu thế nào ...",
      text6: "Làn sóng đắp mặt nạ giấy  không chỉ  loan khắp  nước hàn quốc .mà còn trở thành  xu hướng  của nhiều  cô gái việt .Thế nhưng, đắp mặt nạ giấy...",
      text7: "15 ngày trước",
      image: "assets/images/image_list_one.png",
      image2: "assets/images/list_two.png"),
  Product(
      price1: "399.000 d",
      price2: "600.000 d",
      text1: "KAYOKO",
      text2: "Bộ mỹ phẩm Kayko",
      text3: "Trị Nám Da Số Một",
      text4: "Nhật Bản Chính Hãng",
      text5: "Mặt nạ giấy - sử dụng nhưu thế nào ...",
      text6: "Làn sóng đắp mặt nạ giấy  không chỉ  loan khắp  nước hàn quốc .mà còn trở thành  xu hướng  của nhiều  cô gái việt .Thế nhưng, đắp mặt nạ giấy...",
      text7: "15 ngày trước",
      image: "assets/images/image_list_one.png",
      image2: "assets/images/list_two.png"),
  Product(
      price1: "399.000 d",
      price2: "600.000 d",
      text1: "KAYOKO",
      text2: "Bộ mỹ phẩm Kayko",
      text3: "Trị Nám Da Số Một",
      text4: "Nhật Bản Chính Hãng",
      text5: "Mặt nạ giấy - sử dụng nhưu thế nào ...",
      text6: "Làn sóng đắp mặt nạ giấy  không chỉ  loan khắp  nước hàn quốc .mà còn trở thành  xu hướng  của nhiều  cô gái việt .Thế nhưng, đắp mặt nạ giấy...",
      text7: "15 ngày trước",
      image: "assets/images/image_list_one.png",
      image2: "assets/images/list_two.png"),
  Product(
      price1: "399.000 d",
      price2: "600.000 d",
      text1: "KAYOKO",
      text2: "Bộ mỹ phẩm Kayko",
      text3: "Trị Nám Da Số Một",
      text4: "Nhật Bản Chính Hãng",
      text5: "Mặt nạ giấy - sử dụng nhưu thế nào ...",
      text6: "Làn sóng đắp mặt nạ giấy  không chỉ  loan khắp  nước hàn quốc .mà còn trở thành  xu hướng  của nhiều  cô gái việt .Thế nhưng, đắp mặt nạ giấy...",
      text7: "15 ngày trước",
      image: "assets/images/image_list_one.png",
      image2: "assets/images/list_two.png"),





];
